name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    uses: vishuops0210/shared-repo/.github/workflows/node-ci.yml@main
    with:
      node-version: '18'
      sonar-project-key: 'bajaj-nodejs'
      docker-repository: 'demo-node-app'
      docker-tag: ${{ github.sha }}
      install-command: 'npm install'
      test-command: 'echo "No tests found" && mkdir -p coverage && echo "" > coverage/lcov.info'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
