name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-pipeline:
    uses: vishuops0210/shared-repo/.github/workflows/ci-nodejs.yml@main
    with:
      node-version: '18'
      sonar-project-key: 'bajaj-nodejs'
      docker-repository: 'demo-node-app'
      docker-tag: ${{ github.sha }}
      max-image-size-mb: '500'
      sonar-exclusions: 'node_modules/**,coverage/**,*.test.js'
      install-command: 'npm install'
      test-command: 'npm run test:ci'
      sonar-args: '-Dsonar.projectName="Bajaj Node.js App" -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
